#ifndef OFFLINEMESSENGER_OPTIONS_H
#define OFFLINEMESSENGER_OPTIONS_H

enum commands{
    LOGIN = 1,
    REGISTER = 2,
    ADDCONTACT = 3,
    SELECTCONTACT = 4,
    SENDMESSAGE = 5,
    SHOWCONTACTS = 6,
    SHOWMESSAGES = 7,
    LOGOUT = 8,
    QUIT = 9
};
enum screens{
    LOGREG,
    CONTACTS
};

#endif //OFFLINEMESSENGER_OPTIONS_H
