#ifndef OFFLINEMESSENGER_OPTIONS_H
#define OFFLINEMESSENGER_OPTIONS_H

enum commands{
    LOGIN = 1,
    REGISTER = 2,
    ADDCONTACT = 3,
    SELECTCONTACT = 4,
    SHOWCONTACTS = 5,
    SHOWMESSAGES = 6,
    LOGOUT = 7,
    QUIT = 8
};
enum screens{
    LOGREG,
    CONTACTS,
    CHAT};

#endif //OFFLINEMESSENGER_OPTIONS_H
